---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: bbl-ci
- name: bbl-state

params:
  BBL_STATE_DIR:

run:
  path: bbl-ci/ci/tasks/test-bosh-ssh/task
