#!/bin/bash

set -e
set -u
set -o pipefail

ROOT_DIR="$(dirname "$(dirname "$(realpath -e "${0}")")")"

: "${GOARCH:?}"
: "${GOOS:?}"
: "${TF_VERSION:?}"

PREFIX="${ROOT_DIR}/terraform/binary_dist"
TARGET="${PREFIX}/terraform"
ARCH="terraform_${TF_VERSION}_${GOOS}_${GOARCH}.zip"
URL="https://releases.hashicorp.com/terraform/${TF_VERSION}/${ARCH}"

if [ -f "${TARGET}" ] && [ -x "${TARGET}" ] && [ "${TF_VERSION}" = "$(CHECKPOINT_DISABLE=true "$TARGET" version -json | jq -r .terraform_version)" ]
then
	echo "info: terraform ${TF_VERSION} already present, skipping download"
	exit 0
fi
echo "info: downloading terraform from: ${URL}"
rm -fr "${TARGET}"
mkdir -p "${PREFIX}"
trap 'rm -vf "${ARCH}"' EXIT
wget -nv -O "$ARCH" "$URL"
unzip -j "$ARCH" terraform -d "${PREFIX}"