#!/bin/bash -exu

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d "${root_dir}/../vendor/github.com/cppforlife/jumpbox-deployment" ]; then
    git clone https://github.com/cppforlife/jumpbox-deployment.git "${root_dir}/../vendor/github.com/cppforlife/jumpbox-deployment"
fi

if [ ! -d "${root_dir}/../vendor/github.com/cloudfoundry/bosh-deployment" ]; then
    git clone https://github.com/cloudfoundry/bosh-deployment.git "${root_dir}/../vendor/github.com/cloudfoundry/bosh-deployment"
fi

pushd ${root_dir}/../
    go-bindata -pkg=bosh -ignore=\\.git -o "bosh/deployment_files.go" \
     "vendor/github.com/cppforlife/jumpbox-deployment/..." \
      "vendor/github.com/cloudfoundry/bosh-deployment/..."
popd