---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/deployment

inputs:
- name: bbl-ci
- name: bosh-bootloader

run:
  path: bbl-ci/ci/tasks/test-bosh-bootloader/task
